server:
  port: 9001 
cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: ${AWSAccessKeyId}
      secret-key: ${AWSSecretKey}
    stack:
      auto: false
spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
  application:
    name: s3-demo
  datasource:
    url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}/Project2
    username: ${TRAINING_DB_USERNAME}
    password: ${TRAINING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none